// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://toecaucrwtywbybviidk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRvZWNhdWNyd3R5d2J5YnZpaWRrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU1MzgzMjQsImV4cCI6MjA3MTExNDMyNH0.0osdYPQRGhWbsl-QNDGKmOcC92ubu2loNEGgJfstQ6g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});